import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {seedDirectory} from '../server/directory.js';import {people} from '../dist/people.js';
import {emptyState,validate,appendLetter,publicState,readLetter,CAPACITY} from '../server/letters.js';import {pinLetter} from '../server/wall.js';
const draft=(extra={})=>validate({id:randomUUID(),mailboxId:'8',message:'A private possibility.',...extra});
test('Stable identities and idempotent seeds preserve existing records and consent',()=>{const s=emptyState();const old={id:randomUUID(),mailboxId:'8',message:'Existing',status:'pending',allowPinToWall:true};s.letters.push(old);assert(seedDirectory(s));const first=JSON.stringify(s);assert.equal(seedDirectory(s),false);assert.equal(JSON.stringify(s),first);assert.equal(s.people.length,15);assert.equal(people[7].name,'ALI LIN');const hero=s.letters.filter(l=>l.mailboxId==='8'&&l!==old);assert.equal(hero.length,8);assert.equal(hero.filter(l=>l.sourceType==='OWNER').length,4);assert.equal(hero.filter(l=>l.mediaType==='COLLABORATION').length,1);assert.equal(old.personId,'ali-lin');assert.equal(old.allowPinToWall,true);assert.equal(old.status,'pending');});
test('Fixed recipient is authoritative and a full mailbox cannot redirect a delivery',()=>{const s=emptyState();const {letter}=appendLetter(s,draft({personId:'mika',sourceType:'OWNER'}),'a');assert.equal(letter.mailboxId,'8');assert.equal(letter.personId,'ali-lin');assert.equal(letter.sourceType,'VISITOR');assert.throws(()=>draft({mailboxId:null}),e=>e.status===400);assert.throws(()=>draft({mediaType:'WORK'}),e=>e.status===400);while(s.letters.length<CAPACITY)s.letters.push({...letter,id:randomUUID()});assert.throws(()=>appendLetter(s,draft(),'b'),e=>e.status===409);assert(s.letters.every(l=>l.mailboxId==='8'));});
test('Real collaboration secrets never enter public read, metadata, wall or replay responses',()=>{const s=emptyState(),input=draft({mediaType:'COLLABORATION',message:'secret-message-19283',contact:'private@example.com',allowPinToWall:true,visibility:'public'}),{letter}=appendLetter(s,input,'a');assert.equal(letter.visibility,'private');assert.equal(letter.allowPinToWall,false);assert.equal(letter.contact,'private@example.com');let output=JSON.stringify(publicState(s));assert(!output.includes('secret-message-19283'));assert(!output.includes('private@example.com'));assert(output.includes('collaboration')||output.includes('COLLABORATION'));assert.throws(()=>readLetter(s,letter.id),e=>e.status===404);assert.throws(()=>pinLetter(s,letter.id),e=>e.status===404);letter.allowPinToWall=true;letter.wallState='pinned';assert.equal(publicState(s).wall.length,0);assert.throws(()=>readLetter(s,letter.id),e=>e.status===404);});
test('Recipient, contact and intent are covered by retry identity; links and email are bounded',()=>{const s=emptyState(),input=draft({mediaType:'COLLABORATION',contact:'hi@example.com'});appendLetter(s,input,'a');assert.equal(appendLetter(s,input,'a').replay,true);for(const change of [{mailboxId:'1'},{contact:'other@example.com'},{mediaType:'LETTER'}])assert.throws(()=>appendLetter(s,{...input,...change},'a'),e=>e.status===409);for(const contact of ['javascript:alert(1)','https://a:b@example.com','hi@example.com\nBCC:bad','https://example.com/\nsecret'])assert.throws(()=>draft({mediaType:'COLLABORATION',contact}),e=>e.status===400);assert.equal(draft({mediaType:'COLLABORATION',contact:'https://example.com'}).contact,'https://example.com/');});
test('Public notes retain consent and owner artifacts are read as plain content',()=>{const s=emptyState();seedDirectory(s);const hero=s.letters.filter(l=>l.mailboxId==='8');const print=hero.find(l=>l.mediaType==='IMAGE');const r=readLetter(s,print.id);assert.equal(r.content.visual,'light');assert.equal(r.allowPinToWall,false);assert.equal(r.sourceType,'OWNER');const {letter}=appendLetter(s,draft({message:'Public note',allowPinToWall:true}),'a');assert.equal(readLetter(s,letter.id).message,'Public note');pinLetter(s,letter.id);assert.equal(publicState(s).wall[0].message,'Public note');});
