import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {validate,emptyState,appendLetter,publicState,chooseMailbox,CAPACITY,clientKey} from '../server/letters.js';
const input=(message='A letter')=>validate({id:randomUUID(),message});
test('Unicode length, whitespace and inert HTML',()=>{assert.throws(()=>input('   '));assert.equal(input('🙂'.repeat(280)).message.length,560);assert.throws(()=>input('🙂'.repeat(281)));assert.equal(input('<script>alert(1)</script>').message,'<script>alert(1)</script>');});
test('URL protocols, credentials and malformed input',()=>{for(const u of ['javascript:alert(1)','data:text/html,test','ftp://site.test','https://u:p@site.test','https://site.test/\nfoo','https:\\site.test'])assert.throws(()=>validate({id:randomUUID(),message:'Hi',optionalUrl:u}));assert.equal(validate({id:randomUUID(),message:'Hi',optionalUrl:'https://example.com'}).optionalUrl,'https://example.com/');});
test('Idempotency and private public projection',()=>{const state=emptyState(),letter=input();appendLetter(state,letter,'a',1000);assert.equal(appendLetter(state,letter,'a',1001).replay,true);assert.equal(state.letters.length,1);assert.throws(()=>appendLetter(state,{...letter,message:'Changed'},'a',1002));const publicData=JSON.stringify(publicState(state));assert(!publicData.includes('message'));assert(!publicData.includes('limits'));assert(!publicData.includes('optionalUrl'));assert(publicData.includes(letter.id));});
test('Persistent rate limit and expiry',()=>{const s=emptyState();appendLetter(s,input(),'a',1000);assert.throws(()=>appendLetter(s,input(),'a',1001),e=>e.status===429);for(let i=1;i<5;i++)appendLetter(s,input(),'a',1000+i*16000);assert.throws(()=>appendLetter(s,input(),'a',99000),e=>e.status===429);appendLetter(s,input(),'a',3601001);assert.equal(s.letters.length,6);});
test('Capacity never exceeded, full wall refuses delivery',()=>{const letters=[];for(let box=1;box<=15;box++)for(let i=0;i<CAPACITY;i++)letters.push({mailboxId:String(box)});assert.throws(()=>chooseMailbox(letters),e=>e.status===409);letters.pop();assert.equal(chooseMailbox(letters),'15');});
test('Weighted categories allow both quiet and crowded boxes',()=>{const letters=[];for(const [id,count]of [['1',20],['2',14]])for(let i=0;i<count;i++)letters.push({mailboxId:id});let calls=0;assert.equal(chooseMailbox(letters,()=>calls++===0?.95:0),'1');calls=0;assert.equal(chooseMailbox(letters,()=>calls++===0?.8:0),'2');});
test('Rate identifiers rotate daily and hide raw IP',()=>{const a=clientKey('127.0.0.1','secret',0);assert.equal(a.length,64);assert.notEqual(a,clientKey('127.0.0.1','secret',86400000));});
test('Real papers reconstruct, spill once and remain assigned after restoration',async()=>{
 const THREE=await import('../dist/vendor/three.module.js');const {createLetterMatter}=await import('../dist/letter-matter.js');
 const memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
 const build=()=>{const scene=new THREE.Scene();const boxes=Array.from({length:15},()=>{const base=new THREE.Group();scene.add(base);return {base,open:true,angle:-1.39,button:{dataset:{}},mail:{moving:[]}} ;});return {scene,boxes};};
 const state=publicState({letters:Array.from({length:20},(_,i)=>({id:'test-'+i,mailboxId:'1'}))});
 let {scene,boxes}=build();let matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);assert.equal(matter.papers.size,20);matter.onDoorChange(0,true);matter.update(2);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);const records=memory.get('unplanned-real-mail-v1');matter.onDoorChange(0,false);matter.onDoorChange(0,true);matter.update(2);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);
 ({scene,boxes}=build());matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);assert.equal(matter.papers.size,20);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);assert.equal(matter.counts[0],20);assert.equal(memory.get('unplanned-real-mail-v1'),records);
});
test('Moderation gates metadata and content, including legacy visibility',async()=>{
 const {readLetter}=await import('../server/letters.js');const visible={...input('Plain <script>text</script>'),mailboxId:'1',createdAt:new Date().toISOString(),status:'visible'};
 const hidden={...input('Hidden secret'),mailboxId:'1',status:'hidden'},pending={...input('Pending secret'),mailboxId:'1',status:'pending'};
 const state={letters:[visible,hidden,pending]};assert.equal(publicState(state).mailboxes[0].letters.length,1);assert.equal(readLetter(state,visible.id).message,visible.message);assert.throws(()=>readLetter(state,hidden.id),e=>e.status===404);assert.throws(()=>readLetter(state,pending.id),e=>e.status===404);
 visible.optionalUrl='javascript:alert(1)';assert.equal(readLetter(state,visible.id).optionalUrl,null);delete visible.status;assert.equal(publicState(state).mailboxes[0].letters.length,1);
});
test('Forms are deterministic and age over years rather than days',async()=>{const {letterForm}=await import('../dist/letter-forms.js');const now=Date.now(),id=randomUUID(),date=new Date(now).toISOString();assert.deepEqual(letterForm(id,date,now),letterForm(id,date,now));assert(letterForm(id,date,now+86400000*3).age<.002);assert(letterForm(id,date,now+86400000*365*3).age>.49);});
test('Only front papers reachable; return rearranges, LOD and identity survive refresh',async()=>{
 const THREE=await import('../dist/vendor/three.module.js');const {createLetterMatter}=await import('../dist/letter-matter.js');const memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
 function build(){const scene=new THREE.Scene(),boxes=Array.from({length:15},()=>{const base=new THREE.Group();scene.add(base);return {base,open:false,angle:0,button:{dataset:{}},mail:{moving:[]}};});return {scene,boxes};}
 const state=publicState({letters:Array.from({length:12},(_,i)=>({id:randomUUID(),mailboxId:'1',createdAt:new Date().toISOString()}))});let {scene,boxes}=build(),matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);assert.equal(matter.reachable().length,0);assert([...matter.papers.values()].every(p=>p.mesh.geometry.attributes.position.count===4));boxes[0].open=true;boxes[0].angle=-1.39;matter.onDoorChange(0,true);assert.equal(matter.reachable().length,3);const item=matter.reachable().at(-1),buried=[...matter.papers.keys()][0];assert.equal(matter.hold(buried),null);const held=matter.hold(item.id);assert.equal(matter.papers.size,12);assert.equal(held.mesh.parent,scene);const before=matter.reachable().map(p=>p.id);matter.returnTarget(held);matter.finishReturn(held);assert(!matter.reachable().map(p=>p.id).includes(held.id));assert.equal(held.mesh.parent,boxes[0].base);assert.equal(matter.counts[0],12);assert(before.some(id=>matter.reachable().some(p=>p.id===id)));
 ({scene,boxes}=build());matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);boxes[0].open=true;boxes[0].angle=-1.39;matter.onDoorChange(0,true);assert(!matter.reachable().map(p=>p.id).includes(held.id));assert.equal(matter.papers.size,12);
});
test('A fallen record returns to its original mailbox without a duplicate',async()=>{
 const THREE=await import('../dist/vendor/three.module.js');const {createLetterMatter}=await import('../dist/letter-matter.js');globalThis.sessionStorage={getItem:()=>null,setItem:()=>{}};const scene=new THREE.Scene(),boxes=Array.from({length:15},()=>{const base=new THREE.Group();scene.add(base);return {base,open:true,angle:-1.39,button:{dataset:{}},mail:{moving:[]}};});const state=publicState({letters:Array.from({length:21},()=>({id:randomUUID(),mailboxId:'1'}))});const matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);matter.onDoorChange(0,true);matter.update(2);const item=matter.reachable().find(p=>p.fallen);assert(item);assert.equal(item.mesh.parent,scene);const held=matter.hold(item.id);matter.returnTarget(held);matter.finishReturn(held);assert.equal(held.mesh.parent,boxes[0].base);assert.equal(held.fallen,false);assert.equal(matter.counts[0],21);assert.equal(matter.papers.size,21);let copies=0;scene.traverse(o=>{if(o.userData.letterId===held.id)copies++;});assert.equal(copies,1);
});
