import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {validate,emptyState,appendLetter,publicState,chooseMailbox,CAPACITY,clientKey} from '../server/letters.js';
const input=(message='A letter')=>validate({id:randomUUID(),message});
test('Unicode length, whitespace and inert HTML',()=>{assert.throws(()=>input('   '));assert.equal(input('🙂'.repeat(280)).message.length,560);assert.throws(()=>input('🙂'.repeat(281)));assert.equal(input('<script>alert(1)</script>').message,'<script>alert(1)</script>');});
test('URL protocols, credentials and malformed input',()=>{for(const u of ['javascript:alert(1)','data:text/html,test','ftp://site.test','https://u:p@site.test','https://site.test/\nfoo','https:\\site.test'])assert.throws(()=>validate({id:randomUUID(),message:'Hi',optionalUrl:u}));assert.equal(validate({id:randomUUID(),message:'Hi',optionalUrl:'https://example.com'}).optionalUrl,'https://example.com/');});
test('Idempotency and private public projection',()=>{const state=emptyState(),letter=input();appendLetter(state,letter,'a',1000);assert.equal(appendLetter(state,letter,'a',1001).replay,true);assert.equal(state.letters.length,1);assert.throws(()=>appendLetter(state,{...letter,message:'Changed'},'a',1002));const publicData=JSON.stringify(publicState(state));assert(!publicData.includes('message'));assert(!publicData.includes('limits'));assert(!publicData.includes('optionalUrl'));assert(publicData.includes(letter.id));});
test('Persistent rate limit and expiry',()=>{const s=emptyState();appendLetter(s,input(),'a',1000);assert.throws(()=>appendLetter(s,input(),'a',1001),e=>e.status===429);for(let i=1;i<5;i++)appendLetter(s,input(),'a',1000+i*16000);assert.throws(()=>appendLetter(s,input(),'a',99000),e=>e.status===429);appendLetter(s,input(),'a',3601001);assert.equal(s.letters.length,6);});
test('Capacity never exceeded, full wall refuses delivery',()=>{const letters=[];for(let box=1;box<=15;box++)for(let i=0;i<CAPACITY;i++)letters.push({mailboxId:String(box)});assert.throws(()=>chooseMailbox(letters),e=>e.status===409);letters.pop();assert.equal(chooseMailbox(letters),'15');});
test('Weighted categories allow both quiet and crowded boxes',()=>{const letters=[];for(const [id,count]of [['1',20],['2',14]])for(let i=0;i<count;i++)letters.push({mailboxId:id});let calls=0;assert.equal(chooseMailbox(letters,()=>calls++===0?.95:0),'1');calls=0;assert.equal(chooseMailbox(letters,()=>calls++===0?.8:0),'2');});
test('Rate identifiers rotate daily and hide raw IP',()=>{const a=clientKey('127.0.0.1','secret',0);assert.equal(a.length,64);assert.notEqual(a,clientKey('127.0.0.1','secret',86400000));});
test('Real papers reconstruct, spill once and remain assigned after restoration',async()=>{
 const THREE=await import('../dist/vendor/three.module.js');const {createLetterMatter}=await import('../dist/letter-matter.js');
 const memory=new Map();globalThis.sessionStorage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
 const build=()=>{const scene=new THREE.Scene();const boxes=Array.from({length:15},()=>{const base=new THREE.Group();scene.add(base);return {base,button:{dataset:{}},mail:{moving:[]}};});return {scene,boxes};};
 const state=publicState({letters:Array.from({length:20},(_,i)=>({id:'test-'+i,mailboxId:'1'}))});
 let {scene,boxes}=build();let matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);assert.equal(matter.papers.size,20);matter.onDoorChange(0,true);matter.update(2);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);const records=memory.get('unplanned-real-mail-v1');matter.onDoorChange(0,false);matter.onDoorChange(0,true);matter.update(2);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);
 ({scene,boxes}=build());matter=createLetterMatter(scene,boxes,{reduced:true});matter.sync(state);assert.equal(matter.papers.size,20);assert.equal([...matter.papers.values()].filter(p=>p.fallen).length,5);assert.equal(matter.counts[0],20);assert.equal(memory.get('unplanned-real-mail-v1'),records);
});
