import assert from 'node:assert/strict';
import * as THREE from '../dist/vendor/three.module.js';
import {createSpillSystem} from '../dist/spill.js';
const storage={value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}};
function fixture(reduced=false,store=storage){const scene=new THREE.Scene();const boxes=Array.from({length:15},(_,i)=>{const base=new THREE.Group();base.position.set((i%3)*1.69-4.79,3.3-Math.floor(i/3)*1.65,0);scene.add(base);const pivot=new THREE.Group();pivot.position.set(-.77,-.093,.453);base.add(pivot);const moving=Array.from({length:i===11?13:11},(_,j)=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.8,.6,3,3));mesh.position.set(0,-.35,.29+j*.008);base.add(mesh);return {id:j<10?'body-'+j:'slot-'+j,role:j<10?'body':'slot',order:j,height:.6,mesh};});return {base,pivot,mail:{moving},rest:i===11?-.14:0,button:{setAttribute(){}},open:false,angle:0};});const system=createSpillSystem(scene,boxes,{storage:store,reduced});return {scene,boxes,system};}
function run(f,seconds){for(let n=0;n<Math.ceil(seconds*120);n++){for(let i=0;i<15;i++){const b=f.boxes[i];b.angle=f.system.doorTarget(i,b.open?-1.39:b.rest);b.pivot.rotation.y=b.angle;}f.system.update(1/120);}}
function open(f,i,value=true){f.boxes[i].open=value;f.system.onDoorChange(i,value);}
let f=fixture();open(f,11);run(f,.17);assert.equal(f.system.snapshot().boxes[11].spilled,false);assert.ok(f.system.doorTarget(11,-1.39)>-.2);open(f,11,false);run(f,1);assert.equal(f.system.snapshot().boxes[11].fallenMail.length,0);
open(f,11);run(f,.30);assert.equal(f.system.snapshot().active,0);run(f,2.4);let hero=f.system.snapshot();assert.equal(hero.boxes[11].fallenMail.length,8);assert.equal(hero.boxes[11].remainingMail,5);assert.equal(hero.active,0);assert.equal(hero.boxes[11].fallenMail.filter(p=>p.placement==='ground').length,6);assert.equal(hero.boxes[11].fallenMail.filter(p=>p.placement==='frame').length,1);
const before=hero.boxes[11].fallenMail;open(f,11,false);run(f,.4);open(f,11);run(f,3);assert.deepEqual(f.system.snapshot().boxes[11].fallenMail,before);assert.equal(f.system.snapshot().active,0);
open(f,3);run(f,3);assert.equal(f.system.snapshot().boxes[3].fallenMail.length,7);assert.equal(f.system.snapshot().active,0);assert.equal(f.system.snapshot().boxes.reduce((n,b)=>n+b.fallenMail.length,0),15);
const restored=fixture();assert.equal(restored.system.snapshot().boxes[11].spilled,true);assert.equal(restored.system.snapshot().active,0);assert.equal(restored.boxes[11].mail.moving.filter(m=>m.fallen).length,8);assert.deepEqual(restored.system.snapshot().boxes[11].fallenMail,before);
const noStore={getItem(){return null;},setItem(){}};const reduced=fixture(true,noStore);open(reduced,11);run(reduced,1);assert.equal(reduced.system.snapshot().active,0);assert.equal(reduced.system.snapshot().boxes[11].fallenMail.length,8);
const both=fixture(false,noStore);open(both,3);open(both,11);run(both,.4);assert.ok(both.system.snapshot().active<=15);run(both,3);assert.equal(both.system.snapshot().active,0);
console.log('PASS: delayed release, cancel, one-time spill, two-box accumulation, reload restoration, reduced motion, capped active simulation.');
